import type { Metadata } from "next";
import '@radix-ui/themes/styles.css'
import "@/app/globals.css"
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <QueryClientProvider>
        <AuthProvider>
          <Theme appearance="light" accentColor="violet">
            <Navbar />
            <main className="p-5">{children}</main>
          </Theme>
          </AuthProvider>
        </QueryClientProvider>

      </body>
    </html>
  );
}
